//! Executable Fiber failure taxonomy metadata.
//! Mirrors `TAXONOMY.md` for doctor output and diagnostic matching.

use serde::Serialize;

/// One stable diagnostic taxonomy entry.
#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TaxonomyEntry {
    pub code: &'static str,
    pub category: &'static str,
    pub sub_category: &'static str,
    pub severity: &'static str,
    pub description: &'static str,
    pub technical_cause: &'static str,
    pub common_triggers: &'static [&'static str],
    pub remediation_steps: &'static [&'static str],
    pub explain_template: &'static str,
    #[serde(skip)]
    pub matchers: &'static [&'static str],
}

/// Returns a taxonomy entry by stable code.
pub fn entry_by_code(code: &str) -> Option<&'static TaxonomyEntry> {
    ENTRIES
        .iter()
        .find(|entry| entry.code.eq_ignore_ascii_case(code))
}

/// MVP Demo 3 taxonomy entries. Keep codes additive and stable.
pub const ENTRIES: &[TaxonomyEntry] = &[
    TaxonomyEntry {
        code: "FIBER_ROUTE_001",
        category: "Route",
        sub_category: "NoRouteToTarget",
        severity: "High",
        description: "FNN could not find any route from the sender to the target node.",
        technical_cause: "The route builder had no graph path that connected source and destination.",
        common_triggers: &["Missing peer connection", "Graph gossip not propagated", "Target pubkey unknown"],
        remediation_steps: &[
            "Connect the participating peers.",
            "Run `fiber run scenarios/network-smoke.yaml`.",
            "Retry after graph nodes are visible.",
        ],
        explain_template: "The payment could not be routed because the sender does not currently know any usable path to the destination.",
        matchers: &["no route", "cannot find route", "unable to find route"],
    },
    TaxonomyEntry {
        code: "FIBER_ROUTE_002",
        category: "Route",
        sub_category: "StaleGraph",
        severity: "Medium",
        description: "The local graph view is stale or incomplete.",
        technical_cause: "The graph RPC view does not reflect recently opened or closed channels.",
        common_triggers: &["Payment immediately after channel setup", "Node restart before gossip catches up"],
        remediation_steps: &[
            "Query `graph_nodes` and `graph_channels`.",
            "Wait for gossip propagation.",
            "Use direct `list_channels` checks for local scenarios.",
        ],
        explain_template: "The graph view appears incomplete. The channel may exist locally, but routing decisions are being made from stale or missing graph data.",
        matchers: &["stale graph", "graph", "gossip"],
    },
    TaxonomyEntry {
        code: "FIBER_ROUTE_003",
        category: "Route",
        sub_category: "RouteBuildFailed",
        severity: "High",
        description: "FNN entered route construction but could not produce a valid candidate route.",
        technical_cause: "The route builder rejected all candidate paths due route, channel, fee, or liquidity constraints.",
        common_triggers: &["Mixed route and liquidity failures", "Disabled channel", "Fee policy conflict"],
        remediation_steps: &[
            "Inspect the nested FNN error.",
            "Apply the more specific liquidity, channel, or fee remediation when present.",
        ],
        explain_template: "FNN started building a route but rejected every candidate. The nested error usually identifies the specific constraint.",
        matchers: &["failed to build route", "route build"],
    },
    TaxonomyEntry {
        code: "FIBER_LIQ_001",
        category: "Liquidity",
        sub_category: "InsufficientOutboundCapacity",
        severity: "High",
        description: "A sender or forwarding hop does not have enough outbound liquidity for the payment amount.",
        technical_cause: "FNN reported max outbound liquidity below the required amount.",
        common_triggers: &[
            "Payment amount exceeds local balance",
            "Channel reserves reduce spendable capacity",
            "One-way test channel is too small",
        ],
        remediation_steps: &[
            "Reduce the payment amount.",
            "Open a larger channel.",
            "Fund or rebalance the outbound side before retrying.",
        ],
        explain_template: "The payment reached route construction, but the outbound side of the channel could not carry the requested amount.",
        matchers: &["insufficient balance", "max outbound liquidity", "insufficient outbound"],
    },
    TaxonomyEntry {
        code: "FIBER_LIQ_002",
        category: "Liquidity",
        sub_category: "DirectionalLiquidityMismatch",
        severity: "High",
        description: "Total channel capacity exists, but it is on the wrong side for this payment direction.",
        technical_cause: "The channel balance distribution cannot forward in the requested direction.",
        common_triggers: &["One-way channel used in reverse", "Previous payments drained the sender side"],
        remediation_steps: &[
            "Send in the supported direction.",
            "Rebalance the channel.",
            "Open a new channel from the paying side.",
        ],
        explain_template: "The channel may have capacity, but not in the direction this payment needs.",
        matchers: &["direction", "remote balance", "local balance"],
    },
    TaxonomyEntry {
        code: "FIBER_LIQ_003",
        category: "Liquidity",
        sub_category: "ChannelReserveExceeded",
        severity: "Medium",
        description: "The apparent channel capacity is reduced by CKB reserve and shutdown requirements.",
        technical_cause: "FNN withholds part of funding amount for commitment and shutdown safety.",
        common_triggers: &["Expecting the full funding amount to be spendable", "Auto-accept reserve on accepting peer"],
        remediation_steps: &[
            "Size test channels above the intended payment amount.",
            "Account for the observed reserve in scenario amounts.",
        ],
        explain_template: "The channel funding amount is not the same as spendable payment liquidity because CKB reserves are held back.",
        matchers: &["reserve", "shutdown"],
    },
    TaxonomyEntry {
        code: "FIBER_LIQ_004",
        category: "Liquidity",
        sub_category: "InboundCapacityUnavailable",
        severity: "Medium",
        description: "The receiver or final hop cannot accept the requested amount.",
        technical_cause: "The destination side lacks inbound capacity on the selected path.",
        common_triggers: &["Receiver-only test topology", "Depleted remote balance"],
        remediation_steps: &[
            "Open capacity toward the receiver.",
            "Use a route with available inbound liquidity.",
        ],
        explain_template: "The route may reach the destination, but the final receiving side cannot accept the amount.",
        matchers: &["inbound capacity", "cannot receive"],
    },
    TaxonomyEntry {
        code: "FIBER_CONN_001",
        category: "Connectivity",
        sub_category: "NodeRpcUnreachable",
        severity: "High",
        description: "The CLI could not reach a node's JSON-RPC endpoint.",
        technical_cause: "HTTP transport failed before an FNN JSON-RPC response was returned.",
        common_triggers: &["Node offline", "Wrong port", "Docker network not running"],
        remediation_steps: &[
            "Run `fiber up`.",
            "Verify the endpoint port.",
            "Run `fiber validate --live`.",
        ],
        explain_template: "The target node did not return a JSON-RPC response. This is a connectivity problem before Fiber payment logic starts.",
        matchers: &["error sending request", "connection refused", "tcp connect error", "deadline has elapsed"],
    },
    TaxonomyEntry {
        code: "FIBER_CONN_002",
        category: "Connectivity",
        sub_category: "PeerDisconnected",
        severity: "Medium",
        description: "The FNN node is reachable, but the required Fiber peer is not connected.",
        technical_cause: "P2P peer count or graph data does not include the expected counterparty.",
        common_triggers: &["Hub-spoke connection failed", "Peer container restarted"],
        remediation_steps: &[
            "Restart with `fiber down && fiber up`.",
            "Confirm peer counts in `node_info`.",
        ],
        explain_template: "The node RPC endpoint works, but the Fiber peer relationship needed for the payment is missing.",
        matchers: &["peer disconnected", "not connected"],
    },
    TaxonomyEntry {
        code: "FIBER_CONN_003",
        category: "Connectivity",
        sub_category: "RpcAuthenticationRequired",
        severity: "Medium",
        description: "The RPC endpoint rejected the request because authentication is required.",
        technical_cause: "The node requires Biscuit authorization for this RPC address.",
        common_triggers: &["Public RPC address", "Missing bearer token"],
        remediation_steps: &[
            "Use localhost DevKit endpoints.",
            "Provide a valid Biscuit token for public nodes.",
        ],
        explain_template: "The RPC request reached a node, but the node requires authorization before serving the method.",
        matchers: &["unauthorized", "authorization", "biscuit", "forbidden"],
    },
    TaxonomyEntry {
        code: "FIBER_CHAN_001",
        category: "Channel",
        sub_category: "ChannelNotReady",
        severity: "High",
        description: "A scenario attempted to use a channel before FNN reported ChannelReady.",
        technical_cause: "The channel is still opening, pending funding, or waiting for CKB confirmation.",
        common_triggers: &["Payment starts immediately after open_channel", "Slow CKB RPC"],
        remediation_steps: &["Wait for `list_channels` to show `ChannelReady` before sending payments."],
        explain_template: "The channel exists but is not yet usable for payment forwarding.",
        matchers: &["not ready", "channelready"],
    },
    TaxonomyEntry {
        code: "FIBER_CHAN_002",
        category: "Channel",
        sub_category: "ChannelOpeningTimedOut",
        severity: "High",
        description: "A channel did not become ready inside the scenario setup timeout.",
        technical_cause: "Funding negotiation or CKB confirmation did not complete before the runner deadline.",
        common_triggers: &["Unfunded generated keys", "CKB RPC timeout", "Peer rejected funding proposal"],
        remediation_steps: &[
            "Run `pnpm balances:nodes`.",
            "Run `pnpm fund:nodes`.",
            "Retry from `fiber reset`.",
        ],
        explain_template: "The scenario waited for the channel to become ready, but setup did not complete in time.",
        matchers: &["did not become ready", "timed out waiting for channel"],
    },
    TaxonomyEntry {
        code: "FIBER_CHAN_003",
        category: "Channel",
        sub_category: "ChannelClosedBeforeReady",
        severity: "High",
        description: "FNN closed the channel during setup before it could become usable.",
        technical_cause: "The channel entered Closed while the runner waited for readiness.",
        common_triggers: &["Same-lock funding source", "Insufficient funding cells", "Public one-way channel"],
        remediation_steps: &[
            "Use distinct funded generated node keys.",
            "Keep one-way channels private.",
        ],
        explain_template: "Channel negotiation started but failed before the channel became usable.",
        matchers: &["closed before becoming ready", "funding tx rejected"],
    },
    TaxonomyEntry {
        code: "FIBER_FEE_001",
        category: "Fee",
        sub_category: "FeeExceedsMaximum",
        severity: "Medium",
        description: "Payment fees exceeded the caller's configured maximum fee.",
        technical_cause: "max_fee_amount or fee tolerance is lower than the route's required fee.",
        common_triggers: &["Very low max_fee", "Multi-hop route with nonzero proportional fees"],
        remediation_steps: &["Increase the max fee.", "Choose a lower-fee route."],
        explain_template: "The payment route was otherwise possible, but fees exceeded the configured ceiling.",
        matchers: &["max fee", "fee exceeds", "fee too high"],
    },
    TaxonomyEntry {
        code: "FIBER_FEE_002",
        category: "Fee",
        sub_category: "FeePolicyMismatch",
        severity: "Medium",
        description: "A hop's fee policy makes the otherwise valid route unusable.",
        technical_cause: "Fee policy conflicts with route constraints.",
        common_triggers: &["Custom node template with strict fees", "Stale fee policy in graph"],
        remediation_steps: &["Inspect channel policies.", "Retry after gossip updates."],
        explain_template: "The selected route conflicts with a hop's advertised fee policy.",
        matchers: &["fee policy", "proportional fee"],
    },
    TaxonomyEntry {
        code: "FIBER_ASSET_001",
        category: "Asset",
        sub_category: "UnsupportedAsset",
        severity: "High",
        description: "The requested asset is not supported by one or more nodes on the path.",
        technical_cause: "The route lacks compatible UDT or CKB funding support.",
        common_triggers: &["Asset absent from udt_whitelist", "CCH requested for non-BTC asset"],
        remediation_steps: &["Use CKB for MVP scenarios.", "Configure all nodes with the same asset script."],
        explain_template: "The payment asset is not available across the route.",
        matchers: &["unsupported asset", "udt", "asset"],
    },
    TaxonomyEntry {
        code: "FIBER_ASSET_002",
        category: "Asset",
        sub_category: "AssetTypeMismatch",
        severity: "High",
        description: "Route candidates disagree on the asset type script.",
        technical_cause: "Channel funding UDT type does not match the requested payment asset.",
        common_triggers: &["Mixed CKB and UDT channels", "Wrong wrapped BTC type script"],
        remediation_steps: &["Recreate channels with matching asset configuration."],
        explain_template: "The route mixes incompatible asset types.",
        matchers: &["type script", "asset type mismatch"],
    },
    TaxonomyEntry {
        code: "FIBER_HTLC_001",
        category: "HTLC",
        sub_category: "TlcTimeout",
        severity: "High",
        description: "A time-locked conditional payment expired before settlement.",
        technical_cause: "The TLC reached its expiry delta without a successful preimage flow.",
        common_triggers: &["Slow or disconnected hop", "Route too long for timeout settings"],
        remediation_steps: &["Increase timeout.", "Use a shorter route.", "Restore connectivity before retrying."],
        explain_template: "The payment's time-locked condition expired before settlement completed.",
        matchers: &["tlc timeout", "htlc timeout", "expired"],
    },
    TaxonomyEntry {
        code: "FIBER_HTLC_002",
        category: "HTLC",
        sub_category: "PaymentFailedTerminal",
        severity: "High",
        description: "FNN reported the payment as terminally failed without a more specific reason.",
        technical_cause: "The payment state reached Failed and exposed failed_error.",
        common_triggers: &["Downstream rejection", "Malformed payment parameters"],
        remediation_steps: &["Inspect failed_error.", "Retry only after the specific cause is corrected."],
        explain_template: "The payment reached a terminal failed state, but no more specific taxonomy rule matched.",
        matchers: &["payment ended with status", "failed_error", "status\":\"failed"],
    },
    TaxonomyEntry {
        code: "FIBER_JAM_001",
        category: "Jamming",
        sub_category: "RateLimitedOrJammed",
        severity: "Medium",
        description: "A node or channel appears to reject traffic due rate limits or jamming controls.",
        technical_cause: "Repeated payment attempts or in-flight TLCs exhaust node/channel policy limits.",
        common_triggers: &["Stress scenario", "Many failed attempts", "Pending TLC buildup"],
        remediation_steps: &["Wait for pending TLCs to clear.", "Reduce concurrent test traffic."],
        explain_template: "The node or channel appears saturated by pending or repeated attempts.",
        matchers: &["rate limit", "jam", "too many"],
    },
    TaxonomyEntry {
        code: "FIBER_CCH_001",
        category: "CrossChainHub",
        sub_category: "GatewayUnavailable",
        severity: "Medium",
        description: "No CCH gateway peer is configured or reachable.",
        technical_cause: "send_btc or receive_btc cannot create an order because no gateway is available.",
        common_triggers: &["Local DevKit network has no CCH operator", "CCH RPC module enabled but gateway absent"],
        remediation_steps: &["Treat CCH as unavailable in local tests.", "Configure a real CCH gateway."],
        explain_template: "The CCH module may exist, but no gateway is available for a live bridge order.",
        matchers: &[
            "gateway unavailable",
            "no cch gateway",
            "cch gateway unavailable",
            "gateway peer",
            "gateway not configured",
        ],
    },
    TaxonomyEntry {
        code: "FIBER_CCH_002",
        category: "CrossChainHub",
        sub_category: "UnsupportedCchAsset",
        severity: "Medium",
        description: "The requested CCH asset is outside the supported BTC/wrapped-BTC bridge.",
        technical_cause: "CCH is an order-based BTC bridge, not a generic multi-asset router.",
        common_triggers: &["Requesting CKB, RUSD, or arbitrary UDT through CCH"],
        remediation_steps: &["Use native Fiber for non-BTC assets.", "Request BTC/wrapped-BTC only."],
        explain_template: "CCH cannot bridge this asset because it only covers the BTC/wrapped-BTC mechanism.",
        matchers: &["unsupported cch asset", "wrapped_btc_type_script", "wrapped btc"],
    },
    TaxonomyEntry {
        code: "FIBER_CCH_003",
        category: "CrossChainHub",
        sub_category: "InvoiceValidationFailed",
        severity: "Medium",
        description: "The supplied Bitcoin or Fiber invoice is malformed or amount mismatched.",
        technical_cause: "The order is invalid before it can advance from Pending.",
        common_triggers: &["Empty btc_pay_req", "Wrong network invoice", "Mismatched amount"],
        remediation_steps: &["Generate a fresh invoice on the correct network.", "Retry with matching amount."],
        explain_template: "The CCH order could not validate the invoice input.",
        matchers: &["btc_pay_req", "fiber_pay_req", "pay_req", "invoice"],
    },
    TaxonomyEntry {
        code: "FIBER_CCH_004",
        category: "CrossChainHub",
        sub_category: "IncomingTlcTimeout",
        severity: "High",
        description: "The incoming CCH leg timed out before the required TLCs arrived.",
        technical_cause: "A Pending order failed before incoming acceptance.",
        common_triggers: &["Missing incoming Fiber payment", "Expired invoice"],
        remediation_steps: &["Recreate the CCH order.", "Complete the incoming leg before expiry."],
        explain_template: "The CCH gateway did not receive the incoming conditional payment before expiry.",
        matchers: &["incoming tlc", "incomingtlc", "pending expired"],
    },
    TaxonomyEntry {
        code: "FIBER_CCH_005",
        category: "CrossChainHub",
        sub_category: "OutgoingPaymentFailed",
        severity: "High",
        description: "The outgoing CCH leg failed while trying to obtain or release the preimage.",
        technical_cause: "The order reached OutgoingInFlight and then Failed.",
        common_triggers: &["Lightning payment failure", "Unreachable outgoing peer", "Insufficient bridge liquidity"],
        remediation_steps: &["Check gateway liquidity.", "Retry with a new order."],
        explain_template: "The CCH incoming leg progressed, but the outgoing bridge payment failed.",
        matchers: &["outgoinginflight", "outgoing in flight", "outgoing payment"],
    },
];
